trigger : none

pool:
  vmImage: 'ubuntu-16.04'

stages:
-stage: firststage
 jobs:
   -job: firstjob
    strategy:
      maxParallel: 0
      matrix:
        JOB1:
          Version: 1.1
          Appoldname: one
          Appnewname: onenew
        JOB2:
          Version: 1.1.1
          Appoldname: two
          Appnewname: tow
        JOB3:
          Version: 1.1.2
          Appoldname: three
          Appnewname: thre
    steps:
    -script:
      echo "$(Version)"
      echo "$(Appoldname)"
      echo "$(Appnewname)"     
     displayName: "Echo Variables"
